# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install lftp
        run: sudo apt install lftp
      - name: Mirror files with lftp
        run:
          lftp ${{ secrets.FTP_SERVER }} -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "
          set net:timeout 60;
          set net:max-retries 20;
          set net:reconnect-interval-multiplier 2;
          set net:reconnect-interval-base 5;
          set ftp:ssl-force true;
          set sftp:auto-confirm yes;
          set ssl:verify-certificate true;
          mirror -v -P 5 -R -n -L -x ^\.git/$ \"www\" \"public_html\";
          quit
          "
