# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install lftp
        run: sudo apt install lftp
      - name: ftp-upload-action
        uses: GenieTim/ftp-action@v4.0.1
        with:
          # FTP host
          host: ${{ secrets.FTP_SERVER }}
          # FTP user
          user: ${{ secrets.FTP_USERNAME }}
          # FTP password
          password: ${{ secrets.FTP_PASSWORD }}
          # Force SSL encryption
          forceSsl: true
          # Local directory
          localDir: "www"
          # Remote directory
          remoteDir: "public_html"
